import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { createHead } from "@vueuse/head";
import { createPinia } from "pinia";
import "./assets/index.postcss";
import axios from "axios";
import "./assets/styles/global.css";
import "./assets/styles/index.postcss";
import "./assets/styles/tailwindcss-preflight.css";
import { i18n } from "@/config/i18n";
axios.defaults.baseURL = "http://localhost:4004";
const head = createHead();
const app = createApp(App);
console.log(router);
app.use(router);
app.use(createPinia());
app.use(head);
app.use(i18n);
app.mount("#app");
