import { createApp, ComponentCustomProperties } from "vue";
import App from "./App.vue";
import router from "./router";
import { createHead } from "@vueuse/head";
import "./assets/styles/index.postcss";
import "./assets/styles/global.css";
import "./assets/styles/tailwindcss-preflight.css";
import axios from "axios";
import { createPinia } from "pinia";
import { VueQueryPlugin } from "vue-query";
import { i18n } from "@/config/i18n";
axios.defaults.baseURL = "http://localhost:4004";
const head = createHead();
const app = createApp(App);
app.use(VueQueryPlugin);
app.use(createPinia());
app.use(router);
app.use(head);
app.use(i18n);
app.mount("#app");
